events {}

http {
    upstream my_gateway {
        server localhost:6776; 
    }

    server {
        listen 80;
        location / {
            proxy_pass http://my_gateway;
            proxy_set_header Host $host;
        }
    }
}
