spring.application.name=LoginTGNep
server.port=8081



app.jwt.refresh-token-expiration=604800000
app.jwt.refresh-threshold=120000
app.jwt.secret=haljldfskjakljfldasjlfjaslfsjaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfj
app.jwt.auth-expiration=900000

spring.kafka.bootstrap-servers = localhost:9092
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.profiles.active=dev

debug=true

application.kafka.topic.otp = otp_mail